name: Android CI

env:
  # The name of the main module repository
  main_project_module: app

  # The name of the Play Store
  playstore_name: Frogobox ID

on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    # The workflow will be dispatched to the default queue
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      # Run Build Project
      - name: Build project
        run: ./gradlew build

      # Create APK Debug
      - name: Build apk debug project (APK) Module >> ${{ env.main_project_module }}
        run: ./gradlew assembleDebug

      # Create APK Release
      - name: Build apk release project (APK) Module >> ${{ env.main_project_module }}
        run: ./gradlew assemble

      # Create Bundle AAB Release
      # Noted for main module build [MAIN-APP-MODULE]:bundleRelease
      - name: Build app bundle release (AAB) Module >> ${{ env.main_project_module }}
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      # Upload Artifact Build
      # Noted For Output [MAIN-APP-MODULE]/build/outputs/
      - name: Upload APK Debug ${{ env.playstore_name }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.repository }} | APK(s) debug generated ${{ env.playstore_name }}
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      # Noted For Output [MAIN-APP-MODULE]/build/outputs/
      - name: Upload APK Release ${{ env.playstore_name }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.repository }} | APK(s) release generated ${{ env.playstore_name }}
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      # Noted For Output [MAIN-APP-MODULE]/build/outputs/
      - name: Upload AAB (App Bundle) Release ${{ env.playstore_name }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.repository }} | App bundle(s) release generated ${{ env.playstore_name }}
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/