name: Android CI

env:
  # The name of the main module repository
  MAIN_APP_MODULE: app

  # The name of the Play Store
  PLAY_STORE_NAME: Frogobox

on:
  # Triggers the workflow on push or pull request events but only for default and protected branches
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:
    # The workflow will be dispatched to the default queue
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      # Run Build Project
      - name: Build project
        run: ./gradlew build

      # Create APK Debug
      - name: Build apk debug project (APK)
        run: ./gradlew assembleDebug

      # Create APK Release
      - name: Build apk release project (APK)
        run: ./gradlew assemble

      # Create Bundle AAB Release
      # Noted for main module build [MAIN-APP-MODULE]:bundleRelease
      - name: Build app bundle release (AAB)
        run: ./gradlew ${{ env.MAIN_APP_MODULE }}:bundleRelease

      # Upload Artifact Build
      # Noted For Output [MAIN-APP-MODULE]/build/outputs/
      - name: Upload APK Debug ${{ env.PLAY_STORE_NAME }}
        uses: actions/upload-artifact@v2
        with:
          name: APK(s) debug generated
          path: ${{ env.MAIN_APP_MODULE }}/build/outputs/apk/debug/

      # Noted For Output [MAIN-APP-MODULE]/build/outputs/
      - name: Upload APK Release ${{ env.PLAY_STORE_NAME }}
        uses: actions/upload-artifact@v2
        with:
          name: APK(s) release generated
          path: ${{ env.MAIN_APP_MODULE }}/build/outputs/apk/release/

      # Noted For Output [MAIN-APP-MODULE]/build/outputs/
      - name: Upload AAB (App Bundle) Release ${{ env.PLAY_STORE_NAME }}
        uses: actions/upload-artifact@v2
        with:
          name: App bundle(s) release generated
          path: ${{ env.MAIN_APP_MODULE }}/build/outputs/bundle/release/